#country codes used by google search
ISO3166rev ={'andorra': 'AD', 'united arab emirates': 'AE', 'afghanistan': 'AF', 'antigua & barbuda': 'AG', 'anguilla': 'AI', 'albania': 'AL', 'armenia': 'AM', 'netherlands antilles': 'AN', 'angola': 'AO', 'antarctica': 'AQ', 'argentina': 'AR', 'american samoa': 'AS', 'austria': 'AT', 'australia': 'AU', 'aruba': 'AW', 'azerbaijan': 'AZ', 'bosnia and herzegovina': 'BA', 'barbados': 'BB', 'bangladesh': 'BD', 'belgium': 'BE', 'burkina faso': 'BF', 'bulgaria': 'BG', 'bahrain': 'BH', 'burundi': 'BI', 'benin': 'BJ', 'bermuda': 'BM', 'brunei darussalam': 'BN', 'bolivia': 'BO', 'brazil': 'BR', 'bahama': 'BS', 'bhutan': 'BT', 'burma (no longer exists)': 'BU', 'bouvet island': 'BV', 'botswana': 'BW', 'belarus': 'BY', 'belize': 'BZ', 'canada': 'CA', 'cocos (keeling) islands': 'CC', 'central african republic': 'CF', 'congo': 'CG', 'switzerland': 'CH', "côte d'ivoire (ivory coast)": 'CI', 'cook iislands': 'CK', 'chile': 'CL', 'cameroon': 'CM', 'china': 'CN', 'colombia': 'CO', 'costa rica': 'CR', 'czechoslovakia (no longer exists)': 'CS', 'cuba': 'CU', 'cape verde': 'CV', 'christmas island': 'CX', 'cyprus': 'CY', 'czech republic': 'CZ', 'german democratic republic (no longer exists)': 'DD', 'germany': 'DE', 'djibouti': 'DJ', 'denmark': 'DK', 'dominica': 'DM', 'dominican republic': 'DO', 'algeria': 'DZ', 'ecuador': 'EC', 'estonia': 'EE', 'egypt': 'EG', 'western sahara': 'EH', 'eritrea': 'ER', 'spain': 'ES', 'ethiopia': 'ET', 'finland': 'FI', 'fiji': 'FJ', 'falkland islands (malvinas)': 'FK', 'micronesia': 'FM', 'faroe islands': 'FO', 'france': 'FR', 'france, metropolitan': 'FX', 'gabon': 'GA', 'united kingdom (great britain)': 'GB', 'grenada': 'GD', 'georgia': 'GE', 'french guiana': 'GF', 'ghana': 'GH', 'gibraltar': 'GI', 'greenland': 'GL', 'gambia': 'GM', 'guinea': 'GN', 'guadeloupe': 'GP', 'equatorial guinea': 'GQ', 'greece': 'GR', 'south georgia and the south sandwich islands': 'GS', 'guatemala': 'GT', 'guam': 'GU', 'guinea-bissau': 'GW', 'guyana': 'GY', 'hong kong': 'HK', 'heard & mcdonald islands': 'HM', 'honduras': 'HN', 'croatia': 'HR', 'haiti': 'HT', 'hungary': 'HU', 'indonesia': 'ID', 'ireland': 'IE', 'israel': 'IL', 'india': 'IN', 'british indian ocean territory': 'IO', 'iraq': 'IQ', 'islamic republic of iran': 'IR', 'iceland': 'IS', 'italy': 'IT', 'jamaica': 'JM', 'jordan': 'JO', 'japan': 'JP', 'kenya': 'KE', 'kyrgyzstan': 'KG', 'cambodia': 'KH', 'kiribati': 'KI', 'comoros': 'KM', 'st. kitts and nevis': 'KN', "korea, democratic people's republic of": 'KP', 'korea, republic of': 'KR', 'kuwait': 'KW', 'cayman islands': 'KY', 'kazakhstan': 'KZ', "lao people's democratic republic": 'LA', 'lebanon': 'LB', 'saint lucia': 'LC', 'liechtenstein': 'LI', 'sri lanka': 'LK', 'liberia': 'LR', 'lesotho': 'LS', 'lithuania': 'LT', 'luxembourg': 'LU', 'latvia': 'LV', 'libyan arab jamahiriya': 'LY', 'morocco': 'MA', 'monaco': 'MC', 'moldova, republic of': 'MD', 'madagascar': 'MG', 'marshall islands': 'MH', 'mali': 'ML', 'mongolia': 'MN', 'myanmar': 'MM', 'macau': 'MO', 'northern mariana islands': 'MP', 'martinique': 'MQ', 'mauritania': 'MR', 'monserrat': 'MS', 'malta': 'MT', 'mauritius': 'MU', 'maldives': 'MV', 'malawi': 'MW', 'mexico': 'MX', 'malaysia': 'MY', 'mozambique': 'MZ', 'namibia': 'NA', 'new caledonia': 'NC', 'niger': 'NE', 'norfolk island': 'NF', 'nigeria': 'NG', 'nicaragua': 'NI', 'netherlands': 'NL', 'norway': 'NO', 'nepal': 'NP', 'nauru': 'NR', 'neutral zone (no longer exists)': 'NT', 'niue': 'NU', 'new zealand': 'NZ', 'oman': 'OM', 'panama': 'PA', 'peru': 'PE', 'french polynesia': 'PF', 'papua new guinea': 'PG', 'philippines': 'PH', 'pakistan': 'PK', 'poland': 'PL', 'st. pierre & miquelon': 'PM', 'pitcairn': 'PN', 'puerto rico': 'PR', 'portugal': 'PT', 'palau': 'PW', 'paraguay': 'PY', 'qatar': 'QA', 'réunion': 'RE', 'romania': 'RO', 'russian federation': 'RU', 'rwanda': 'RW', 'saudi arabia': 'SA', 'solomon islands': 'SB', 'seychelles': 'SC', 'sudan': 'SD', 'sweden': 'SE', 'singapore': 'SG', 'st. helena': 'SH', 'slovenia': 'SI', 'svalbard & jan mayen islands': 'SJ', 'slovakia': 'SK', 'sierra leone': 'SL', 'san marino': 'SM', 'senegal': 'SN', 'somalia': 'SO', 'suriname': 'SR', 'sao tome & principe': 'ST','union of soviet socialist republics (no longer exists)': 'SU', 'el salvador': 'SV', 'syrian arab republic': 'SY', 'swaziland': 'SZ', 'turks & caicos islands': 'TC', 'chad': 'TD', 'french southern territories': 'TF', 'togo': 'TG', 'thailand': 'TH', 'tajikistan': 'TJ', 'tokelau': 'TK', 'turkmenistan': 'TM', 'tunisia': 'TN', 'tonga': 'TO', 'east timor': 'TP', 'turkey': 'TR', 'trinidad & tobago': 'TT', 'tuvalu': 'TV', 'taiwan, province of china': 'TW', 'tanzania, united republic of': 'TZ', 'ukraine': 'UA', 'uganda': 'UG', 'united states minor outlying islands': 'UM', 'united states of america': 'US', 'uruguay': 'UY', 'uzbekistan': 'UZ', 'vatican city state (holy see)': 'VA', 'st. vincent & the grenadines': 'VC', 'venezuela': 'VE', 'british virgin islands': 'VG', 'united states virgin islands': 'VI', 'viet nam': 'VN', 'vanuatu': 'VU', 'wallis & futuna islands': 'WF', 'samoa': 'WS', 'democratic yemen (no longer exists)': 'YD', 'yemen': 'YE', 'mayotte': 'YT', 'yugoslavia': 'YU', 'south africa': 'ZA', 'zambia': 'ZM', 'zaire': 'ZR', 'zimbabwe': 'ZW', 'unknown or unspecified country': 'ZZ'}

ISO3166 = {
	'AD': 'Andorra',
	'AE': 'United Arab Emirates',
	'AF': 'Afghanistan',
	'AG': 'Antigua & Barbuda',
	'AI': 'Anguilla',
	'AL': 'Albania',
	'AM': 'Armenia',
	'AN': 'Netherlands Antilles',
	'AO': 'Angola',
	'AQ': 'Antarctica',
	'AR': 'Argentina',
	'AS': 'American Samoa',
	'AT': 'Austria',
	'AU': 'Australia',
	'AW': 'Aruba',
	'AZ': 'Azerbaijan',
	'BA': 'Bosnia and Herzegovina',
	'BB': 'Barbados',
	'BD': 'Bangladesh',
	'BE': 'Belgium',
	'BF': 'Burkina Faso',
	'BG': 'Bulgaria',
	'BH': 'Bahrain',
	'BI': 'Burundi',
	'BJ': 'Benin',
	'BM': 'Bermuda',
	'BN': 'Brunei Darussalam',
	'BO': 'Bolivia',
	'BR': 'Brazil',
	'BS': 'Bahama',
	'BT': 'Bhutan',
	'BU': 'Burma (no longer exists)',
	'BV': 'Bouvet Island',
	'BW': 'Botswana',
	'BY': 'Belarus',
	'BZ': 'Belize',
	'CA': 'Canada',
	'CC': 'Cocos (Keeling) Islands',
	'CF': 'Central African Republic',
	'CG': 'Congo',
	'CH': 'Switzerland',
	'CI': 'Côte D\'ivoire (Ivory Coast)',
	'CK': 'Cook Iislands',
	'CL': 'Chile',
	'CM': 'Cameroon',
	'CN': 'China',
	'CO': 'Colombia',
	'CR': 'Costa Rica',
	'CS': 'Czechoslovakia (no longer exists)',
	'CU': 'Cuba',
	'CV': 'Cape Verde',
	'CX': 'Christmas Island',
	'CY': 'Cyprus',
	'CZ': 'Czech Republic',
	'DD': 'German Democratic Republic (no longer exists)',
	'DE': 'Germany',
	'DJ': 'Djibouti',
	'DK': 'Denmark',
	'DM': 'Dominica',
	'DO': 'Dominican Republic',
	'DZ': 'Algeria',
	'EC': 'Ecuador',
	'EE': 'Estonia',
	'EG': 'Egypt',
	'EH': 'Western Sahara',
	'ER': 'Eritrea',
	'ES': 'Spain',
	'ET': 'Ethiopia',
	'FI': 'Finland',
	'FJ': 'Fiji',
	'FK': 'Falkland Islands (Malvinas)',
	'FM': 'Micronesia',
	'FO': 'Faroe Islands',
	'FR': 'France',
	'FX': 'France, Metropolitan',
	'GA': 'Gabon',
	'GB': 'United Kingdom (Great Britain)',
	'GD': 'Grenada',
	'GE': 'Georgia',
	'GF': 'French Guiana',
	'GH': 'Ghana',
	'GI': 'Gibraltar',
	'GL': 'Greenland',
	'GM': 'Gambia',
	'GN': 'Guinea',
	'GP': 'Guadeloupe',
	'GQ': 'Equatorial Guinea',
	'GR': 'Greece',
	'GS': 'South Georgia and the South Sandwich Islands',
	'GT': 'Guatemala',
	'GU': 'Guam',
	'GW': 'Guinea-Bissau',
	'GY': 'Guyana',
	'HK': 'Hong Kong',
	'HM': 'Heard & McDonald Islands',
	'HN': 'Honduras',
	'HR': 'Croatia',
	'HT': 'Haiti',
	'HU': 'Hungary',
	'ID': 'Indonesia',
	'IE': 'Ireland',
	'IL': 'Israel',
	'IN': 'India',
	'IO': 'British Indian Ocean Territory',
	'IQ': 'Iraq',
	'IR': 'Islamic Republic of Iran',
	'IS': 'Iceland',
	'IT': 'Italy',
	'JM': 'Jamaica',
	'JO': 'Jordan',
	'JP': 'Japan',
	'KE': 'Kenya',
	'KG': 'Kyrgyzstan',
	'KH': 'Cambodia',
	'KI': 'Kiribati',
	'KM': 'Comoros',
	'KN': 'St. Kitts and Nevis',
	'KP': 'Korea, Democratic People\'s Republic of',
	'KR': 'Korea, Republic of',
	'KW': 'Kuwait',
	'KY': 'Cayman Islands',
	'KZ': 'Kazakhstan',
	'LA': 'Lao People\'s Democratic Republic',
	'LB': 'Lebanon',
	'LC': 'Saint Lucia',
	'LI': 'Liechtenstein',
	'LK': 'Sri Lanka',
	'LR': 'Liberia',
	'LS': 'Lesotho',
	'LT': 'Lithuania',
	'LU': 'Luxembourg',
	'LV': 'Latvia',
	'LY': 'Libyan Arab Jamahiriya',
	'MA': 'Morocco',
	'MC': 'Monaco',
	'MD': 'Moldova, Republic of',
	'MG': 'Madagascar',
	'MH': 'Marshall Islands',
	'ML': 'Mali',
	'MN': 'Mongolia',
	'MM': 'Myanmar',
	'MO': 'Macau',
	'MP': 'Northern Mariana Islands',
	'MQ': 'Martinique',
	'MR': 'Mauritania',
	'MS': 'Monserrat',
	'MT': 'Malta',
	'MU': 'Mauritius',
	'MV': 'Maldives',
	'MW': 'Malawi',
	'MX': 'Mexico',
	'MY': 'Malaysia',
	'MZ': 'Mozambique',
	'NA': 'Namibia',
	'NC': 'New Caledonia',
	'NE': 'Niger',
	'NF': 'Norfolk Island',
	'NG': 'Nigeria',
	'NI': 'Nicaragua',
	'NL': 'Netherlands',
	'NO': 'Norway',
	'NP': 'Nepal',
	'NR': 'Nauru',
	'NT': 'Neutral Zone (no longer exists)',
	'NU': 'Niue',
	'NZ': 'New Zealand',
	'OM': 'Oman',
	'PA': 'Panama',
	'PE': 'Peru',
	'PF': 'French Polynesia',
	'PG': 'Papua New Guinea',
	'PH': 'Philippines',
	'PK': 'Pakistan',
	'PL': 'Poland',
	'PM': 'St. Pierre & Miquelon',
	'PN': 'Pitcairn',
	'PR': 'Puerto Rico',
	'PT': 'Portugal',
	'PW': 'Palau',
	'PY': 'Paraguay',
	'QA': 'Qatar',
	'RE': 'Réunion',
	'RO': 'Romania',
	'RU': 'Russian Federation',
	'RW': 'Rwanda',
	'SA': 'Saudi Arabia',
	'SB': 'Solomon Islands',
	'SC': 'Seychelles',
	'SD': 'Sudan',
	'SE': 'Sweden',
	'SG': 'Singapore',
	'SH': 'St. Helena',
	'SI': 'Slovenia',
	'SJ': 'Svalbard & Jan Mayen Islands',
	'SK': 'Slovakia',
	'SL': 'Sierra Leone',
	'SM': 'San Marino',
	'SN': 'Senegal',
	'SO': 'Somalia',
	'SR': 'Suriname',
	'ST': 'Sao Tome & Principe',
	'SU': 'Union of Soviet Socialist Republics (no longer exists)',
	'SV': 'El Salvador',
	'SY': 'Syrian Arab Republic',
	'SZ': 'Swaziland',
	'TC': 'Turks & Caicos Islands',
	'TD': 'Chad',
	'TF': 'French Southern Territories',
	'TG': 'Togo',
	'TH': 'Thailand',
	'TJ': 'Tajikistan',
	'TK': 'Tokelau',
	'TM': 'Turkmenistan',
	'TN': 'Tunisia',
	'TO': 'Tonga',
	'TP': 'East Timor',
	'TR': 'Turkey',
	'TT': 'Trinidad & Tobago',
	'TV': 'Tuvalu',
	'TW': 'Taiwan, Province of China',
	'TZ': 'Tanzania, United Republic of',
	'UA': 'Ukraine',
	'UG': 'Uganda',
	'UM': 'United States Minor Outlying Islands',
	'US': 'United States of America',
	'UY': 'Uruguay',
	'UZ': 'Uzbekistan',
	'VA': 'Vatican City State (Holy See)',
	'VC': 'St. Vincent & the Grenadines',
	'VE': 'Venezuela',
	'VG': 'British Virgin Islands',
	'VI': 'United States Virgin Islands',
	'VN': 'Viet Nam',
	'VU': 'Vanuatu',
	'WF': 'Wallis & Futuna Islands',
	'WS': 'Samoa',
	'YD': 'Democratic Yemen (no longer exists)',
	'YE': 'Yemen',
	'YT': 'Mayotte',
	'YU': 'Yugoslavia',
	'ZA': 'South Africa',
	'ZM': 'Zambia',
	'ZR': 'Zaire',
	'ZW': 'Zimbabwe',
	'ZZ': 'Unknown or unspecified country',
}